server:
  port: ${PORT:8080}

firebase:
  service-account-filename: client-path-d-firebase-adminsdk-61yys-296abb182f.json
  realtime-database-url: https://client-path-d.firebaseio.com # for example https://your-application.firebaseio.com
